dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # traj_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joints:
  #     - arm_joint_2

  # vel_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: arm_joint_1

  pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_1
    # pid: {p: 100.0, i: 0.001, d: 10.0}

dynamixel_control:
  serial_interface: /dev/ttyACM0
  loop_frequency: 10
  cycle_time_error_threshold: 0.002
  baudrate: 1000000 # in bauds
  read_timeout: 0.005 # in seconds
  scan_timeout: 0.005 # in seconds
  # Cofniguration of the servos
  servos:
    arm_joint_1:
      # hardware ID of the actuator
      id: 1
      #offset: 3.14159265359
      # offset to be added, in radians, to the position of an actuator
      #max-speed: 4.0 # in rad
      command_interface: position
    # arm_joint_2:
    #   id: 2
    #   # max joint speed
    #   # it shoud NOT be used for actuators in velocity mode
    #   offset: 3.1 # in rad/s
    #   # this actuator is set in reverse mode for the speed and position
    #   #reverse: false
  # default mode
  default_command_interface: position
